export const FILTERS_APPLIED = 'FILTERS_APPLIED';

// Register
export const REGISTER_FORM_SUBMITTED = 'REGISTER_FORM_SUBMITTED';
export const REGISTER_FORM_SUCCEED = 'REGISTER_FORM_SUCCEED';
export const REGISTER_FORM_FAILED = 'REGISTER_FORM_FAILED';
export const EMAIL_UPDATE_REQUEST_SUBMITTED = 'EMAIL_UPDATE_REQUEST_SUBMITTED';
export const EMAIL_UPDATE_REQUEST_SUCCEED = 'EMAIL_UPDATE_REQUEST_SUCCEED';
export const EMAIL_UPDATE_REQUEST_FAILED = 'EMAIL_UPDATE_REQUEST_FAILED';
export const EMAIL_UPDATE_FORM_SUBMITTED = 'EMAIL_UPDATE_FORM_SUBMITTED';
export const EMAIL_UPDATE_FORM_SUCCEED = 'EMAIL_UPDATE_FORM_SUCCEED';
export const EMAIL_UPDATE_FORM_FAILED = 'EMAIL_UPDATE_FORM_FAILED';
export const EMAIL_REQUEST_VERIFICATION_SUBMITTED = 'EMAIL_REQUEST_VERIFICATION_SUBMITTED';
export const EMAIL_REQUEST_VERIFICATION_SUCCEED = 'EMAIL_REQUEST_VERIFICATION_SUCCEED';
export const EMAIL_REQUEST_VERIFICATION_FAILED = 'EMAIL_REQUEST_VERIFICATION_FAILED';

// Login
export const AUTOLOGIN_SUBMITTED = 'AUTOLOGIN_SUBMITTED';
export const AUTOLOGIN_SUCCEED = 'AUTOLOGIN_SUCCEED';
export const AUTOLOGIN_FAILED = 'AUTOLOGIN_FAILED';
export const LOGIN_FORM_SUBMITTED = 'LOGIN_FORM_SUBMITTED';
export const LOGIN_FORM_SUCCEED = 'LOGIN_FORM_SUCCEED';
export const LOGIN_FORM_FAILED = 'LOGIN_FORM_FAILED';
export const REQUEST_RESET_LINK_FORM_SUBMITTED = 'REQUEST_RESET_LINK_FORM_SUBMITTED';
export const REQUEST_RESET_LINK_FORM_SUCCEED = 'REQUEST_RESET_LINK_FORM_SUCCEED';
export const REQUEST_RESET_LINK_FORM_FAILED = 'REQUEST_RESET_LINK_FORM_FAILED';
export const RESET_PASSWORD_FORM_SUBMITTED = 'RESET_PASSWORD_FORM_SUBMITTED';
export const RESET_PASSWORD_FORM_SUCCEED = 'RESET_PASSWORD_FORM_SUCCEED';
export const RESET_PASSWORD_FORM_FAILED = 'RESET_PASSWORD_FORM_FAILED';

// Social
export const CONNECT_SOCIAL_NETWORK = 'CONNECT_SOCIAL_NETWORK';
export const PUBLISH_SOCIAL_PROFILE = 'PUBLISH_SOCIAL_PROFILE';
export const LINKEDIN_LOGIN_SUBMITTED = 'LINKEDIN_LOGIN_SUBMITTED';
export const LINKEDIN_LOGIN_SUCCEED = 'LINKEDIN_LOGIN_SUCCEED';
export const LINKEDIN_LOGIN_FAILED = 'LINKEDIN_LOGIN_FAILED';
export const LINKEDIN_LOGOUT_SUBMITTED = 'LINKEDIN_LOGOUT_SUBMITTED';
export const LINKEDIN_LOGOUT_SUCCEED = 'LINKEDIN_LOGOUT_SUCCEED';
export const LINKEDIN_LOGOUT_FAILED = 'LINKEDIN_LOGOUT_FAILED';
export const FACEBOOK_LOGIN_SUBMITTED = 'FACEBOOK_LOGIN_SUBMITTED';
export const FACEBOOK_LOGIN_SUCCEED = 'FACEBOOK_LOGIN_SUCCEED';
export const FACEBOOK_LOGIN_FAILED = 'FACEBOOK_LOGIN_FAILED';
export const FACEBOOK_LOGOUT_SUBMITTED = 'FACEBOOK_LOGOUT_SUBMITTED';
export const FACEBOOK_LOGOUT_SUCCEED = 'FACEBOOK_LOGOUT_SUCCEED';
export const FACEBOOK_LOGOUT_FAILED = 'FACEBOOK_LOGOUT_FAILED';
export const INSTAGRAM_LOGIN_SUBMITTED = 'INSTAGRAM_LOGIN_SUBMITTED';
export const INSTAGRAM_LOGIN_SUCCEED = 'INSTAGRAM_LOGIN_SUCCEED';
export const INSTAGRAM_LOGIN_FAILED = 'INSTAGRAM_LOGIN_FAILED';
export const INSTAGRAM_LOGOUT_SUBMITTED = 'INSTAGRAM_LOGOUT_SUBMITTED';
export const INSTAGRAM_LOGOUT_SUCCEED = 'INSTAGRAM_LOGOUT_SUCCEED';
export const INSTAGRAM_LOGOUT_FAILED = 'INSTAGRAM_LOGOUT_FAILED';

// Account
export const ACCOUNT_REQUESTED = 'ACCOUNT_REQUESTED';
export const ACCOUNT_UPDATED = 'ACCOUNT_UPDATED';
export const ACCOUNT_NOT_UPDATED = 'ACCOUNT_NOT_UPDATED';

export const ACCOUNT_FORM_SUBMITTED = 'ACCOUNT_FORM_SUBMITTED';
export const ACCOUNT_FORM_SUCCEED = 'ACCOUNT_FORM_SUCCEED';
export const ACCOUNT_FORM_FAILED = 'ACCOUNT_FORM_FAILED';
export const EMAIL_VALIDATION_SUBMITTED = 'EMAIL_VALIDATION_SUBMITTED';
export const EMAIL_VALIDATION_SUCCEED = 'EMAIL_VALIDATION_SUCCEED';
export const EMAIL_VALIDATION_FAILED = 'EMAIL_VALIDATION_FAILED';

// Logout
export const LOGOUT_SUBMITTED = 'LOGOUT_SUBMITTED';
export const LOGOUT_SUCCEED = 'LOGOUT_SUCCEED';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

// Companies
export const COMPANIES_REQUESTED = 'COMPANIES_REQUESTED';
export const COMPANIES_UPDATED = 'COMPANIES_UPDATED';
export const COMPANIES_NOT_UPDATED = 'COMPANIES_NOT_UPDATED';

export const COMPANY_REQUESTED = 'COMPANY_REQUESTED';
export const COMPANY_UPDATED = 'COMPANY_UPDATED';
export const COMPANY_NOT_UPDATED = 'COMPANY_NOT_UPDATED';

export const COMPANY_CREATE_FORM_SUBMITTED = 'COMPANY_CREATE_FORM_SUBMITTED';
export const COMPANY_CREATE_FORM_SUCCEED = 'COMPANY_CREATE_FORM_SUCCEED';
export const COMPANY_CREATE_FORM_FAILED = 'COMPANY_CREATE_FORM_FAILED';

export const COMPANY_SELECTED = 'COMPANY_SELECTED';

export const COMPANY_UPDATE_FORM_SUBMITTED = 'COMPANY_UPDATE_FORM_SUBMITTED';
export const COMPANY_UPDATE_FORM_SUCCEED = 'COMPANY_UPDATE_FORM_SUCCEED';
export const COMPANY_UPDATE_FORM_FAILED = 'COMPANY_UPDATE_FORM_FAILED';

export const COMPANY_DELETE_SUBMITTED = 'COMPANY_DELETE_SUBMITTED';
export const COMPANY_DELETE_SUCCEED = 'COMPANY_DELETE_SUCCEED';
export const COMPANY_DELETE_FAILED = 'COMPANY_DELETE_FAILED';

export const PICTURE_UPLOAD_FORM_SUBMITTED = 'PICTURE_UPLOAD_FORM_SUBMITTED';
export const PICTURE_UPLOAD_FORM_SUCCEED = 'PICTURE_UPLOAD_FORM_SUCCEED';
export const PICTURE_UPLOAD_FORM_FAILED = 'PICTURE_UPLOAD_FORM_FAILED';

// Modules
export const MODULES_REQUESTED = 'MODULES_REQUESTED';
export const MODULES_UPDATED = 'MODULES_UPDATED';
export const MODULES_NOT_UPDATED = 'MODULES_NOT_UPDATED';

export const MODULES_NOTIFICATIONS_FORM_SUBMITTED = 'MODULES_NOTIFICATIONS_FORM_SUBMITTED';
export const MODULES_NOTIFICATIONS_FORM_SUCCEED = 'MODULES_NOTIFICATIONS_FORM_SUCCEED';
export const MODULES_NOTIFICATIONS_FORM_FAILED = 'MODULES_NOTIFICATIONS_FORM_FAILED';

// Activities
export const ACTIVITIES_REQUESTED = 'ACTIVITIES_REQUESTED';
export const ACTIVITIES_UPDATED = 'ACTIVITIES_UPDATED';
export const ACTIVITIES_NOT_UPDATED = 'ACTIVITIES_NOT_UPDATED';
export const ACTIVITIES_PAGINATE = 'ACTIVITIES_PAGINATE';
export const ACTIVITIES_RESET_PAGINATION = 'ACTIVITIES_RESET_PAGINATION';

// Roles
export const ROLES_REQUESTED = 'ROLES_REQUESTED';
export const ROLES_UPDATED = 'ROLES_UPDATED';
export const ROLES_NOT_UPDATED = 'ROLES_NOT_UPDATED';

export const ROLE_FORM_SUBMITTED = 'ROLE_FORM_SUBMITTED';
export const ROLE_FORM_SUCCEED = 'ROLE_FORM_SUCCEED';
export const ROLE_FORM_FAILED = 'ROLE_FORM_FAILED';

export const ROLE_STATUS_SUBMITTED = 'ROLE_STATUS_SUBMITTED';
export const ROLE_STATUS_SUCCEED = 'ROLE_STATUS_SUCCEED';
export const ROLE_STATUS_FAILED = 'ROLE_STATUS_FAILED';

export const ROLE_SELECTED = 'ROLE_SELECTED';

// Forms
export const FORM_RESET = 'FORM_RESET';

// Notifier
export const NOTIFIER_NOTIFICATION_DISPLAYED = 'NOTIFIER_NOTIFICATION_DISPLAYED';
export const NOTIFIER_NOTIFICATION_REMOVED = 'NOTIFIER_NOTIFICATION_REMOVED';

// Contact
export const CONTACT_FORM_SUBMITTED = 'CONTACT_FORM_SUBMITTED';
export const CONTACT_FORM_SUCCEED = 'CONTACT_FORM_SUCCEED';
export const CONTACT_FORM_FAILED = 'CONTACT_FORM_FAILED';

// Feedback
export const FEEDBACK_FORM_SUBMITTED = 'FEEDBACK_FORM_SUBMITTED';
export const FEEDBACK_FORM_SUCCEED = 'FEEDBACK_FORM_SUCCEED';
export const FEEDBACK_FORM_FAILED = 'FEEDBACK_FORM_FAILED';
