export const SEASONS_FETCH = 'SEASONS_FETCH';
export const SEASONS_SUCCESS = 'SEASONS_SUCCESS';
export const SEASONS_FAILURE = 'SEASONS_FAILURE';

export const SEASON_SELECT = 'SEASON_SELECT';

export const DIVISIONS_FETCH = 'DIVISIONS_FETCH';
export const DIVISIONS_SUCCESS = 'DIVISIONS_SUCCESS';
export const DIVISIONS_FAILURE = 'DIVISIONS_FAILURE';
