export const SEASONS_FETCH = 'SEASONS_FETCH';
export const SEASONS_SUCCESS = 'SEASONS_SUCCESS';
export const SEASONS_FAILURE = 'SEASONS_FAILURE';

export const SEASON_SELECT = 'SEASON_SELECT';

export const SEASON_SUMMARY_FETCH = 'SEASON_SUMMARY_FETCH';
export const SEASON_SUMMARY_SUCCESS = 'SEASON_SUMMARY_SUCCESS';
export const SEASON_SUMMARY_FAILURE = 'SEASON_SUMMARY_FAILURE';

export const DIVISIONS_FETCH = 'DIVISIONS_FETCH';
export const DIVISIONS_SUCCESS = 'DIVISIONS_SUCCESS';
export const DIVISIONS_FAILURE = 'DIVISIONS_FAILURE';

export const DIVISION_FETCH = 'DIVISION_FETCH';
export const DIVISION_SUCCESS = 'DIVISION_SUCCESS';
export const DIVISION_FAILURE = 'DIVISION_FAILURE';
